# Generated by Django 6.1 on 2026-08-25 17:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_cuit', models.CharField(db_index=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Debe contener exactamente 8 u 11 dígitos.', regex='^(\\d{8}|\\d{11})$')], verbose_name='DNI o CUIT')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre / Razón Social')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remito_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='N° de Remito')),
                ('sender', models.CharField(max_length=255, verbose_name='Remitente')),
                ('deposit_number', models.CharField(max_length=100, verbose_name='N° Depósito / Destino')),
                ('logistics_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Logística / Transporte interno')),
                ('packages', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bultos')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Peso (Kgs)')),
                ('declared_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Declarado')),
                ('value_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Valor')),
                ('received_datetime', models.DateTimeField(verbose_name='Fecha y Hora de Recibido')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='api.client', verbose_name='Consignatario (Cliente)')),
            ],
            options={
                'verbose_name': 'Despacho / Remito',
                'verbose_name_plural': 'Despachos / Remitos',
                'ordering': ['-received_datetime'],
            },
        ),
    ]
