# Generated by Django 6.1 on 2026-08-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="value_type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Tipo de Valor",
            ),
        ),
    ]